#[derive(Copy, Clone, PartialEq)]
pub(crate) enum Instruction {
    Constant(usize),
    Nil,
    True,
    False,
    Pop,
    GetLocal(usize),
    SetLocal(usize),
    GetGlobal(usize),
    DefineGlobal(usize),
    SetGlobal(usize),
    Equal,
    Greater,
    Less,
    Add,
    Subtract,
    Multiply,
    Divide,
    Not,
    Negate,
    Jump(usize),
    JumpIfFalse(usize),
    Loop(usize),
    Call(usize),
    Closure(usize),
    Return,
}
